In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
cite_fake_new = pd.read_csv("./Processed_data/Cite_fake_New.csv")

In [3]:
cite_fake_new

,TitleID,Authors,Title,Source title,Proceeding,Volume,Paper Area,Type,Conference Type,Paper Type,Approval,Chair_or_Editor1,Chair_or_Editor2
0,0,"Gautam A., Crandall J.W., Goodrich M.A.",Self-assessment of Proficiency of Intelligent ...,Proceedings of the ASME Design Engineering Tec...,1210 AISC,NaN,Drones; Human engineering; Intelligent systems...,Conference,Regular Conference,Full Paper,Yes,Chair 1,Chair 2
1,1,"de Moura Oliveira P.B., Hedengren J.D., Boaven...",Bridging theory to practice: Feedforward and c...,Proceedings of the ASME Design Engineering Tec...,695 LNEE,NaN,Automation; Cascade control systems; Computati...,Conference,Regular Conference,Full Paper,Yes,Chair 1,Chair 2
2,2,"Hajimirzaie S.M., Hotchkiss R.H.",Development of sediment management guidelines ...,IEEE Transactions on Antennas and Propagation,NaN,146,Hydraulics; Editorial board; Sediment manageme...,Journal,NaN,Short Paper,Yes,Editor 1,Editor 2
3,3,"Bunnell S., Gorrell S., Salmon J., Thelin C., ...",Structural design space exploration using prin...,Proceedings of the ASME Design Engineering Tec...,20,NaN,Compressors; Data handling; Structural design;...,Conference,Regular Conference,Poster,Yes,Chair 1,Chair 2
4,4,"Richardson M., Cannon S., Teichert L., Vance A...",Religion-focused dating apps: A Q methodology ...,IEEE Transactions on Antennas and Propagation,NaN,14,Entertainment; A-RINGS; External pressures; Ro...,Journal,NaN,Demo Paper,No,Editor 1,Editor 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,885,"Hovanski Y., Mishra R., Sato Y., Upadhyay P., ...",Preface,Proceedings of the International Telemetering ...,81,NaN,Databases,Conference,Regular Conference,Poster,Yes,Chair 9,Chair 10
886,886,"Rice M., Hogstrom C., Nash C., Ravert J., Saqu...",A summary of data-aided equalizer experiments ...,Proceedings of SPIE - The International Societ...,199,NaN,Bit error rate; Quadrature phase shift keying;...,Conference,Expert Group,Short Paper,Yes,Chair 5,Chair 6
887,887,"Upadhyay P., Hovanski Y., Carlson B., Boettche...",Joining Dissimilar Material Using Friction Sti...,Optics InfoBase Conference Papers,150,NaN,Aluminum; Automobile manufacture; Carbon steel...,Conference,Symposium,Poster,Yes,Chair 3,Chair 4
888,888,"Yuan Y., Rai A., Yeung E., Stan G.-B., Warnick...",A minimal realization technique for the dynami...,Optics InfoBase Conference Papers,4,NaN,Complex networks; Structured programming; Caus...,Conference,Symposium,Short Paper,Yes,Chair 3,Chair 4
889,889,"Hansen N.C., Allen B.L., Anapalli S., Blacksha...",Dryland agriculture in north america,International Journal of Heat and Mass Transfer,NaN,153,Crops; Efficiency; Herbicides; Soils; Water co...,Journal,NaN,Full Paper,Yes,Editor 5,Editor 6

In [4]:
Proceeding_Volume = cite_fake_new[["Proceeding","Volume"]]

In [9]:
Proceeding_Volume["Proceeding"].unique().shape[0]

253

In [10]:
np.random.randint(low = 10, high = 100, size = 253)

array([45, 32, 73, 93, 76, 67, 79, 26, 36, 93, 69, 10, 35, 51, 93, 73, 58,
       88, 38, 27, 53, 29, 90, 74, 19, 20, 33, 44, 20, 32, 10, 29, 40, 79,
       92, 80, 30, 78, 73, 97, 55, 56, 43, 48, 10, 59, 68, 36, 38, 56, 38,
       89, 33, 61, 98, 99, 21, 39, 45, 61, 94, 55, 47, 53, 87, 31, 53, 47,
       69, 53, 34, 64, 11, 13, 43, 97, 88, 54, 61, 59, 49, 62, 56, 66, 58,
       62, 78, 62, 68, 12, 92, 67, 48, 34, 49, 74, 64, 58, 98, 87, 24, 67,
       93, 39, 71, 84, 62, 64, 37, 80, 37, 40, 76, 35, 49, 83, 73, 71, 17,
       96, 76, 20, 50, 85, 35, 63, 40, 62, 97, 30, 46, 23, 37, 97, 27, 52,
       26, 81, 24, 13, 17, 45, 43, 20, 41, 89, 37, 61, 96, 83, 17, 64, 48,
       72, 15, 70, 28, 85, 12, 45, 56, 54, 40, 64, 63, 22, 51, 76, 59, 40,
       11, 23, 57, 60, 10, 38, 73, 69, 27, 46, 88, 57, 21, 54, 30, 79, 39,
       39, 17, 23, 41, 65, 90, 13, 14, 54, 25, 94, 13, 36, 64, 77, 42, 97,
       85, 56, 99, 14, 34, 21, 43, 20, 93, 99, 75, 84, 44, 68, 23, 14, 31,
       73, 45, 70, 27, 11, 11, 78, 85, 69, 22, 66, 38, 72, 68, 77, 40, 21,
       86, 88, 78, 54, 29, 11, 14, 59, 78, 79, 12, 77, 81, 75, 35])

In [12]:
Proceeding_Mapping = pd.DataFrame([Proceeding_Volume["Proceeding"].unique(),np.random.randint(low = 10, high = 100, size = 253)]).T

             0     1
0    1210 AISC    81
1     695 LNEE    34
2          NaN  63.0
3           20    33
4          189    54
..         ...   ...
248        246    78
249         41    94
250         82    64
251        155    94
252      10127    88

[253 rows x 2 columns]

In [15]:
Proceeding_Mapping = Proceeding_Mapping.loc[pd.isnull(Proceeding_Mapping[0]) == False ].rename(columns = {0:"Proceeding",1:"Num_of_Pages"}
                                                                                              )
Proceeding_Mapping

    Proceeding Num_of_Pages
0    1210 AISC           81
1     695 LNEE           34
3           20           33
4          189           54
5           60           82
..         ...          ...
248        246           78
249         41           94
250         82           64
251        155           94
252      10127           88

[252 rows x 2 columns]

In [16]:
Proceeding_Mapping.to_csv("./Processed_data/Proceeding_Mapping.csv",index=False,encoding="utf_8_sig")

In [17]:
Proceeding_Volume["Volume"].unique().shape[0]

154

In [18]:
Volume_Mapping = pd.DataFrame([Proceeding_Volume["Volume"].unique(),np.random.randint(low = 10, high = 100, size = 154)]).T
Volume_Mapping

              0     1
0           NaN  52.0
1           146    74
2            14    44
3           122    34
4           270    58
..          ...   ...
149          41    68
150         352    65
151  2017-April    90
152     2B-2017    56
153         179    73

[154 rows x 2 columns]

In [19]:
Volume_Mapping = Volume_Mapping.loc[pd.isnull(Volume_Mapping[0]) == False ].rename(columns = {0:"Volume",1:"Num_of_Pages"}
                                                                                              )
Volume_Mapping

         Volume Num_of_Pages
1           146           74
2            14           44
3           122           34
4           270           58
5           178           85
..          ...          ...
149          41           68
150         352           65
151  2017-April           90
152     2B-2017           56
153         179           73

[153 rows x 2 columns]

In [ ]:
Volume__Mapping.to_csv("./Processed_data/Proceeding_Mapping.csv",index=False,encoding="utf_8_sig")